### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by alex-b-chase** [COL-IU/FragGeneScan#1]
I am having trouble installing this software. I am hoping to use it in combination with MaxBin and this is a dependency.
I get the error:

> hmm_lib.c:1005:4: warning: implicit declaration of function 'get_rc_dna_indel' is invalid in C99
>       [-Wimplicit-function-declaration]
>           get_rc_dna_indel(dna_f, dna_f1);
>           ^
> 1 warning generated.
> gcc    -c -o run_hmm.o run_hmm.c
> run_hmm.c:93:5: warning: implicit declaration of function 'print_usage' is invalid in C99
>       [-Wimplicit-function-declaration]
>     print_usage();
>     ^
> run_hmm.c:519:1: warning: control reaches end of non-void function [-Wreturn-type]
> }
> ^
> 2 warnings generated.
> gcc  -O3 -o FragGeneScan util_lib.o hmm_lib.o run_hmm.o  -lm -lpthread

**Comment by wazimismail** [comment]
Hi. I don't think these warnings will affect the functioning of the code. These warnings can be ignored. Thanks.
